engines:
  golint:
    enabled: true
  govet:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript

ratings:
  paths:
    - "**.go"
    - "**.js"
    - "**.css"


